language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t nhukangasniemi/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true nhukangasniemi/docker-react npm run test